### ISSUE TITLE
BooleanField default value error

### ISSUE THREAD

**Issue by giantatwork** [ankitjaiswal07/django-offline#1]
When running makemigrations on Django 1.6 the following error occurs:

_offline.Config.value: (1_6.W002) BooleanField does not have a default value.
    HINT: Django 1.6 changed the default value of BooleanField from False to None. See https://docs.djangoproject.com/en/1.6/ref/models/fields/#booleanfield for more information._

This can be fixed by providing a default value to the BooleanField in models.py.
Unfortunately I don't have access to create a pull request.

**Comment by ankitjaiswal07** [comment]
Hi giantatwork, thanks for reporting this bug. This has been handled now. Please let me know if you still face some issues with the library.
